# Generated by Django 5.2.5 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_googleoauthcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.CharField(db_index=True, help_text='A unique token for the user, used for authentication.', max_length=255, null=True),
        ),
    ]
