# Generated by Django 5.2.5 on 2025-09-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='googleoauthstate',
            index=models.Index(fields=['state'], name='users_googl_state_42c641_idx'),
        ),
        migrations.AddIndex(
            model_name='googleoauthstate',
            index=models.Index(fields=['created_at'], name='users_googl_created_24b164_idx'),
        ),
    ]
