services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    container_name: tasks-to-habit
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: restart
          path: ./
          target: ./code
    restart: unless-stopped

  cron:
      build:
        context: .
        dockerfile: Dockerfile.dev
      entrypoint: ./entrypoint-cron.sh
      container_name: tasks-to-habit-cron
      volumes:
        - .:/code
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Kolkata
      develop:
        watch:
          - action: restart
            path: ./
            target: ./code
      restart: unless-stopped
