FROM python:3.10-slim
# Install cron
RUN apt-get update && apt-get install -y cron
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY requirements-dev.txt .
COPY requirements.txt .
RUN pip install -r requirements-dev.txt
COPY . .
