services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    container_name: tasks-to-habit
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
