# Generated by Django 5.2.5 on 2025-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id', 'due'], name='tasks_task_task_id_fbee2b_idx'),
        ),
    ]
