# Generated by Django 5.2.5 on 2025-09-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_tasks_task_task_id_fbee2b_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'due'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_list', 'task_id', 'due')},
        ),
    ]
