# Generated by Django 5.2.5 on 2025-09-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        ('tasks', '0003_alter_task_options_alter_task_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='associated_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
